### ISSUE TITLE
Поддержка compass

### ISSUE THREAD

**Issue by m1skam** [olegpro/bitrix-csscompiler#4]
Олег, если не сложно, можно добавить это расширение? https://github.com/leafo/scssphp-compass
Поясню, compass дает огромное кол-во плюшек для scss, киллер фича это - генерация спрайтов или генерация инлайн base64 картинок или файлов шрифтов.

**Comment by drapeza** [comment]
Почемуто через несколько часов после установки модуль перестал работать, не могу найти в чем причина. Переустанавливать модуль пробовал - не помогло

**Comment by olegpro** [comment]
В чём конкретно выражается «неработость» модуля?

**Comment by drapeza** [comment]
Изменяю scss файл, а css не обновляется

**Comment by olegpro** [comment]
права запись есть?

SHOW_ERRORS_IN_DISPLAY есть такой параметр. Если установить его в Y ошибки компонента будут выводиться на экран, если N то будут записываться функцией AddMessage2Log()

**Comment by drapeza** [comment]
О, спасибо, действительно у меня ошибка из-за отсутствия compass'a
