### ISSUE TITLE
Ошибка парсинга файлов с кириллическими комментариями

### ISSUE THREAD

**Issue by artvaleev** [olegpro/bitrix-csscompiler#5]
Если в scss файлах есть кириллические комментарии, то scssphp выдает ошибку парсинга, и, собственно, обрывает работу битрикса.
Текст ошибки такой (библиотека scssphp свежая с гитхаба):
[Leafo\ScssPhp\Exception\ParserException] 
parse error: failed at `*/
` (stdin) on line 3 (0)
bitrix\modules\olegpro.csscompiler\libs\scssphp\src\Parser.php:120

**Comment by olegpro** [comment]
Это касается работы библиотеки ScssPhp. Создайте им [issue](https://github.com/leafo/scssphp/issues/new).

**Comment by pafnuty** [comment]
@artvaleev попробуйте отключить `mbstring.internal_encoding = UTF-8`, 
а для `mbstring.func_overload = 2` задать 0

Похожая проблема был в less компиляторе https://github.com/oyejorge/less.php/issues/38 и её удалось решить https://github.com/oyejorge/less.php/pull/237
возможно тут тоже самое т.к. такую "смесь" конфига php очень, очень редко используют в мире :smile:

**Comment by artvaleev** [comment]
@pafnuty эти настройки требует битрикс еще перед установкой, так что не стал их трогать.
@olegpro разработчик библиотеки пофиксил этот баг, и обновил библиотеку, теперь все работает ок. Но он не уточнил, что кодировка файлов должна быть utf-8. При cp1251 все равно падает, но это уже не критично, имхо.

**Comment by olegpro** [comment]
@artvaleev тогда обновлю ScssPhp, как зарелизится.

**Comment by olegpro** [comment]
Обновил модуль и вместе с ним scssphp. Коммит: 306388b0a91e7e89f4fce1b9415680cfe60d1d2a 

Апдейт уже в маркетплейсе.
