### ISSUE TITLE
Долго компилирует

### ISSUE THREAD

**Issue by Sam116** [olegpro/bitrix-csscompiler#6]
С чем может быть связана очень долгая работа компилятора? До этого использовал версию 1.0.3, работало отлично, на другом проекте установил последнюю версию(1.1) и стало очень долго компилить при изменении файла. Попробовал залить на новый проект компонент с прошлого проекта, это не помогло, так же долго компилит, а потом еще выдает сверху страницы Line 195 WARN:   на такую констуркцию в файле миксинов, но после обновления страницы этот варнинг исчезает.
     
@else if $class == w400 {
        @media only screen and (max-width: 400px) { @content; }
    }
    @else {
        @warn "Breakpoint mixin supports: w1300, w1200, w1000, w800, w650, w550, w450, w400";
    }

**Comment by olegpro** [comment]
Вам [сюда](https://github.com/leafo/scssphp/issues/new), если вы про scss
